remote_theme: coursweb/jk-theme
title: Portfolio
description: Base d'un cours sur la création de portfolio web
lang: fr-FR
# robots: noindex, nofollow
# markdown: GFM
chapters:
 - title: Cours-web
   url: https://cours-web.ch/
 - title: Créativité
   url: https://cours-web.ch/crea/
footer_col_1: <ul class="contact-list">
  <li>Eracom, Lausanne</li>
  <li>2022</li></ul>
footer_col_2: <ul class="social-media-list"><li><a href="https://github.com/coursweb/portfolio">Lien Github</a></li></ul>
